"""Comprehensive master catalogue of Indian Kirana and grocery store products.

Contains over 110 daily essential products with variants, prices, and rich
multilingual search keywords in English, Telugu, and Hindi.
"""

MASTER_PRODUCTS = [
    # --- STAPLES: SUGAR & JAGGERY ---
    ("Madhur Pure Refined Sugar", "Madhur", "Staples", "1kg", 48.0, 52.0, 60,
     "sugar cheeni panchadara shakkar madhur sweet meetha chini", "Sulphur-free pure refined crystal sugar 1kg"),
    ("Madhur Pure Refined Sugar", "Madhur", "Staples", "2kg", 95.0, 104.0, 50,
     "sugar cheeni panchadara shakkar madhur 2kg 2kgs chini", "Sulphur-free pure refined crystal sugar 2kg pouch"),
    ("Madhur Pure Refined Sugar", "Madhur", "Staples", "5kg", 235.0, 260.0, 30,
     "sugar cheeni panchadara shakkar madhur 5kg 5kgs", "Sulphur-free pure refined crystal sugar 5kg family pack"),
    ("Organic Jaggery Block / Bellam", "Organic Tattva", "Staples", "1kg", 75.0, 85.0, 40,
     "jaggery gur bellam god bellamu organic sweet", "Pure chemical-free golden jaggery bellam 1kg"),
    ("Organic Jaggery Powder / Bellam", "Organic Tattva", "Staples", "500g", 45.0, 50.0, 40,
     "jaggery powder gur bellam podi shakkar", "Natural granulated jaggery powder 500g"),

    # --- STAPLES: ATTA, FLOURS & GRAINS ---
    ("Aashirvaad Shudh Chakki Atta", "Aashirvaad", "Staples", "1kg", 55.0, 60.0, 40,
     "atta wheat flour godhuma pindi roti chapati chakki 1kg", "100% whole wheat traditional chakki atta 1kg"),
    ("Aashirvaad Shudh Chakki Atta", "Aashirvaad", "Staples", "5kg", 245.0, 260.0, 30,
     "atta wheat flour godhuma pindi roti chapati chakki 5kg", "100% whole wheat traditional chakki atta 5kg"),
    ("Aashirvaad Shudh Chakki Atta", "Aashirvaad", "Staples", "10kg", 475.0, 500.0, 20,
     "atta wheat flour godhuma pindi roti chapati chakki 10kg", "100% whole wheat traditional chakki atta 10kg"),
    ("Fortune Maida All Purpose Flour", "Fortune", "Staples", "1kg", 45.0, 50.0, 40,
     "maida all purpose flour refined wheat pindi baking parotta", "Fine quality refined maida flour 1kg"),
    ("Fortune Besan Gram Flour", "Fortune", "Staples", "500g", 55.0, 60.0, 45,
     "besan gram flour senagapindi chana dal flour pakoda", "Pure 100% chana dal fine besan 500g"),
    ("Fortune Besan Gram Flour", "Fortune", "Staples", "1kg", 105.0, 115.0, 40,
     "besan gram flour senagapindi chana dal flour 1kg", "Pure 100% chana dal fine besan 1kg"),
    ("Bombay Rava / Sooji", "Nature Fresh", "Staples", "1kg", 50.0, 55.0, 45,
     "sooji suji rava ravva bombay rava upma semolina", "Premium granulated bombay sooji rava 1kg"),
    ("Idli Rava", "Nature Fresh", "Staples", "1kg", 52.0, 58.0, 45,
     "idli rava ravva idly rice rava tiffin breakfast", "Finely milled idli rice rava 1kg"),
    ("Thick Poha / Atukulu", "Tata Sampann", "Staples", "500g", 38.0, 45.0, 40,
     "poha atukulu flattened rice chivda aval avalakki", "High-fibre thick pressed poha 500g"),

    # --- STAPLES: RICE ---
    ("Sona Masoori Raw Rice", "Sri Krishna Select", "Staples", "5kg", 310.0, 340.0, 40,
     "rice chawal biyyam sona masoori raw rice 5kg", "Aged lightweight aromatic sona masoori rice 5kg"),
    ("Sona Masoori Raw Rice", "Sri Krishna Select", "Staples", "10kg", 590.0, 650.0, 30,
     "rice chawal biyyam sona masoori raw rice 10kg", "Aged premium sona masoori rice 10kg bag"),
    ("Sona Masoori Raw Rice (25kg Bag)", "Sri Krishna Select", "Staples", "25kg Bag", 1420.0, 1550.0, 15,
     "rice bag 25kg bag sona masoori biyyam chawal wholesale", "Wholesale 25kg bag of aged sona masoori rice"),
    ("India Gate Basmati Rice", "India Gate", "Staples", "1kg", 130.0, 145.0, 40,
     "rice basmati chawal biyyam long grain biryani pulao", "Aromatic long grain basmati rice 1kg"),
    ("India Gate Basmati Rice", "India Gate", "Staples", "5kg", 590.0, 650.0, 25,
     "rice basmati chawal biyyam long grain biryani 5kg", "Aromatic long grain feast basmati rice 5kg"),

    # --- STAPLES: DALS & PULSES ---
    ("Tata Sampann Toor Dal", "Tata Sampann", "Staples", "1kg", 160.0, 175.0, 40,
     "toor dal kandi pappu arhar dal pulses lentils sambar dal", "Unpolished protein-rich toor dal 1kg"),
    ("Tata Sampann Toor Dal", "Tata Sampann", "Staples", "500g", 85.0, 92.0, 40,
     "toor dal kandi pappu arhar dal 500g pulses", "Unpolished protein-rich toor dal 500g"),
    ("Moong Dal Yellow Split", "Tata Sampann", "Staples", "1kg", 140.0, 155.0, 35,
     "moong dal yellow split pesara pappu mung dal pulses", "Nutritious easy to digest yellow moong dal 1kg"),
    ("Moong Dal Yellow Split", "Tata Sampann", "Staples", "500g", 75.0, 82.0, 40,
     "moong dal yellow pesara pappu 500g", "Nutritious yellow moong dal 500g"),
    ("Chana Dal", "Fortune", "Staples", "1kg", 110.0, 125.0, 40,
     "chana dal senaga pappu bengal gram dal pulses", "Clean sorted premium chana dal 1kg"),
    ("Urad Dal White Whole", "Tata Sampann", "Staples", "1kg", 155.0, 170.0, 40,
     "urad dal minapa pappu minumulu white whole idli dosa dal", "High quality white whole urad dal 1kg"),
    ("Urad Dal White Whole", "Tata Sampann", "Staples", "500g", 82.0, 90.0, 40,
     "urad dal minapa pappu 500g idli dosa", "High quality white whole urad dal 500g"),
    ("Kabuli Chana (White Chickpeas)", "Tata Sampann", "Staples", "1kg", 135.0, 150.0, 30,
     "kabuli chana chole vella senagalu chickpeas white chana", "Big grain kabuli chana for chole 1kg"),
    ("Rajma Chitra Kashmiri", "Tata Sampann", "Staples", "1kg", 145.0, 165.0, 30,
     "rajma kidney beans chitra kashmiri pulses", "Kashmiri chitra delicious soft cooking rajma 1kg"),
    ("Whole Green Moong", "Tata Sampann", "Staples", "1kg", 130.0, 145.0, 30,
     "green moong pesalu sprouts whole mung sabut", "Whole green moong for sprouts and curries 1kg"),

    # --- STAPLES: OILS & GHEE ---
    ("Fortune Refined Sunflower Oil", "Fortune", "Staples", "1 L", 145.0, 160.0, 50,
     "oil sunflower tel nune refined cooking fortune 1l", "Light and healthy refined sunflower oil 1 litre"),
    ("Freedom Refined Sunflower Oil", "Freedom", "Staples", "1 L", 142.0, 155.0, 50,
     "oil sunflower tel nune refined cooking freedom 1l", "Triple refined healthy sunflower oil 1 litre pouch"),
    ("Saffola Gold Blended Oil", "Saffola", "Staples", "1 L", 175.0, 195.0, 40,
     "saffola gold oil heart cooking blended tel nune 1l", "Pro healthy heart blended cooking oil 1 litre"),
    ("Fortune Pure Mustard Oil", "Fortune", "Staples", "1 L", 155.0, 170.0, 30,
     "mustard oil sarson tel kachi ghani avalu nune 1l", "Authentic strong kachi ghani mustard oil 1 litre"),
    ("Gemini Pure Groundnut Oil", "Gemini", "Staples", "1 L", 185.0, 205.0, 30,
     "groundnut oil verusenaga nune peanut oil cooking 1l", "Filtered pure groundnut peanut cooking oil 1 litre"),
    ("Amul Pure Ghee", "Amul", "Dairy", "500ml", 310.0, 330.0, 40,
     "ghee neyyi ghi cow pure amul butter fat 500ml", "Aromatic pure cow ghee in tin / pack 500ml"),
    ("Amul Pure Ghee", "Amul", "Dairy", "1 L", 610.0, 650.0, 30,
     "ghee neyyi ghi cow pure amul butter 1l 1litre", "Aromatic pure cow ghee 1 litre carton"),
    ("GRB Pure Cow Ghee", "GRB", "Dairy", "500ml", 335.0, 360.0, 30,
     "grb ghee neyyi cow pure traditional aroma 500ml", "Granulated traditional aroma cow ghee 500ml jar"),

    # --- STAPLES: SPICES, SALTS & CONDIMENTS ---
    ("Tata Salt Vacuum Evaporated", "Tata", "Staples", "1kg", 28.0, 28.0, 60,
     "salt namak uppu iodised groceries cooking tata salt 1kg", "Desh ka namak pure iodised vacuum evaporated salt 1kg"),
    ("Tata Salt Lite (Low Sodium)", "Tata", "Staples", "1kg", 45.0, 48.0, 30,
     "salt lite low sodium namak uppu bp healthy", "Low sodium healthy iodised salt 1kg"),
    ("Rock Salt / Sendha Namak", "Catch", "Staples", "1kg", 55.0, 65.0, 30,
     "rock salt sendha namak saindhava lavanam vrat fasting", "Natural pink rock salt sendha namak 1kg"),
    ("Aashirvaad Pure Chilli Powder", "Aashirvaad", "Staples", "200g", 78.0, 85.0, 50,
     "chilli powder mirchi kaaram mirapakaya lal mirch masala", "Bright red spicy pure chilli powder 200g"),
    ("Aashirvaad Pure Chilli Powder", "Aashirvaad", "Staples", "500g", 185.0, 205.0, 40,
     "chilli powder mirchi kaaram mirapakaya lal mirch 500g", "Bright red spicy pure chilli powder 500g"),
    ("Everest Turmeric Powder / Haldi", "Everest", "Staples", "200g", 48.0, 55.0, 50,
     "turmeric haldi pasupu powder spice yellow masala", "Pure natural golden turmeric powder 200g"),
    ("Everest Coriander Powder / Dhaniya", "Everest", "Staples", "200g", 45.0, 50.0, 50,
     "dhaniya coriander dhaniyalu kothimeera powder spice", "Aromatic ground coriander powder 200g"),
    ("Everest Garam Masala", "Everest", "Staples", "100g", 75.0, 85.0, 45,
     "garam masala spice curry kitchen king everest", "Royal blend of 13 exotic spices garam masala 100g"),
    ("Catch Black Pepper Powder", "Catch", "Staples", "100g", 95.0, 110.0, 30,
     "pepper black pepper miriyalu kali mirch powder", "Pungent fresh ground black pepper powder 100g sprinkler"),
    ("Cumin Seeds / Jeera", "Catch", "Staples", "200g", 90.0, 105.0, 40,
     "jeera jeelakarra cumin seeds whole spice tadka", "Whole clean aromatic cumin seeds jeera 200g"),
    ("Mustard Seeds / Rai / Aavalu", "Catch", "Staples", "200g", 35.0, 42.0, 40,
     "mustard seeds rai aavalu whole spice tadka", "Clean black mustard seeds aavalu 200g"),
    ("Ginger Garlic Paste", "Dabur Hommade", "Staples", "200g", 50.0, 55.0, 45,
     "ginger garlic paste adrak lehsun allam vellulli paste", "Thick and fresh ginger garlic paste 200g pouch"),
    ("Kissan Fresh Tomato Ketchup", "Kissan", "Staples", "950g", 120.0, 145.0, 30,
     "ketchup tomato sauce kissan bottle snacks", "Sweet and tangy fresh tomato ketchup 950g bottle"),

    # --- DAIRY & REFRIGERATED ---
    ("Amul Taaza Toned Milk", "Amul", "Dairy", "500ml", 27.0, 27.0, 50,
     "milk doodh paalu fresh dairy taaza toned 500ml", "Pasteurised toned milk 500ml pouch"),
    ("Amul Taaza Toned Milk", "Amul", "Dairy", "1 L", 54.0, 54.0, 50,
     "milk doodh paalu fresh dairy taaza 1l 1litre", "Pasteurised toned milk 1 litre pouch"),
    ("Amul Gold Full Cream Milk", "Amul", "Dairy", "500ml", 33.0, 33.0, 50,
     "milk doodh paalu gold cream dairy full cream 500ml", "Rich high-fat full cream milk 500ml"),
    ("Amul Gold Full Cream Milk", "Amul", "Dairy", "1 L", 66.0, 66.0, 50,
     "milk doodh paalu gold cream dairy 1l 1litre", "Rich high-fat full cream milk 1 litre"),
    ("Nandini GoodLife Toned Milk UHT", "Nandini", "Dairy", "500ml", 28.0, 30.0, 40,
     "milk nandini goodlife uht tetra pack long life 500ml", "UHT treated long life toned milk 500ml tetra pack"),
    ("Fresh Malai Paneer", "Amul", "Dairy", "200g", 90.0, 95.0, 40,
     "paneer cottage cheese dairy cooking malai paneer 200g", "Soft and fresh rich paneer cubes 200g"),
    ("Fresh Malai Paneer", "Amul", "Dairy", "500g", 210.0, 230.0, 25,
     "paneer cottage cheese dairy cooking malai 500g", "Soft and fresh rich paneer block 500g"),
    ("Amul Masti Dahi Curd", "Amul", "Dairy", "400g", 40.0, 40.0, 50,
     "curd dahi perugu yogurt dairy masti amul 400g", "Thick probiotic set curd 400g cup"),
    ("Amul Masti Dahi Curd", "Amul", "Dairy", "1kg", 85.0, 90.0, 30,
     "curd dahi perugu yogurt dairy masti amul 1kg", "Thick probiotic curd 1kg pouch"),
    ("Amul Salted Butter", "Amul", "Dairy", "100g", 58.0, 60.0, 45,
     "butter makhan venna salted dairy amul 100g", "Delicious classic salted butter 100g"),
    ("Amul Salted Butter", "Amul", "Dairy", "500g", 275.0, 290.0, 25,
     "butter makhan venna salted dairy amul 500g", "Delicious classic salted butter 500g family block"),
    ("Britannia Cheese Slices", "Britannia", "Dairy", "200g (10 Slices)", 135.0, 150.0, 30,
     "cheese slices cheddar britannia sandwich burger", "Creamy processed cheddar cheese slices 10 pack"),
    ("Amul Cheese Cubes", "Amul", "Dairy", "200g", 130.0, 140.0, 30,
     "cheese cubes amul dairy pizza sandwich", "Tasty pasteurised processed cheese cubes 200g"),

    # --- BAKERY & EGGS ---
    ("Britannia Milk Bread", "Britannia", "Bakery", "400g", 45.0, 45.0, 40,
     "bread loaf bakery breakfast toast white bread 400g", "Soft enriched daily white milk bread 400g"),
    ("Britannia Brown Bread", "Britannia", "Bakery", "400g", 55.0, 55.0, 35,
     "bread brown wheat bakery healthy breakfast 400g", "Nutritious whole wheat brown bread 400g"),
    ("Britannia 100% Whole Wheat Bread", "Britannia", "Bakery", "400g", 50.0, 50.0, 35,
     "bread atta wheat whole wheat healthy bakery", "Healthy 100% whole wheat atta bread 400g"),
    ("Fresh Pav Buns", "Local Bakery", "Bakery", "6 pcs", 30.0, 30.0, 30,
     "pav bun buns pavbhaji vada pav bakery 6 pack", "Freshly baked soft pav buns pack of 6"),
    ("Farm Fresh White Eggs", "Farm Fresh", "Bakery", "Tray of 6", 45.0, 50.0, 50,
     "eggs egg anda guddu breakfast protein 6 pack", "Nutritious farm fresh protein rich eggs pack of 6"),
    ("Farm Fresh White Eggs", "Farm Fresh", "Bakery", "Tray of 12", 88.0, 95.0, 40,
     "eggs egg anda guddu breakfast 12 pack dozen", "Farm fresh protein rich eggs pack of 12"),
    ("Farm Fresh White Eggs", "Farm Fresh", "Bakery", "Tray of 30", 210.0, 240.0, 20,
     "eggs egg anda guddu tray wholesale 30 eggs", "Farm fresh eggs complete tray of 30"),
    ("Kellogg's Corn Flakes", "Kellogg's", "Bakery", "500g", 185.0, 205.0, 25,
     "cornflakes cereal breakfast kelloggs milk cereal", "Crispy original corn flakes cereal 500g"),
    ("Quaker Rolled White Oats", "Quaker", "Bakery", "1kg", 175.0, 199.0, 30,
     "oats quaker rolled porridge breakfast healthy fiber", "100% whole grain nutritious breakfast oats 1kg"),

    # --- BEVERAGES & TEA / COFFEE ---
    ("Tata Tea Gold Leaf Tea", "Tata Tea", "Beverages", "500g", 310.0, 330.0, 35,
     "tea chai patti tea powder tata tea gold 500g", "Exquisite aroma and rich taste tea powder 500g"),
    ("Tata Tea Gold Leaf Tea", "Tata Tea", "Beverages", "250g", 160.0, 175.0, 40,
     "tea chai patti tea powder tata tea gold 250g", "Exquisite aroma and rich taste tea powder 250g"),
    ("Brooke Bond Red Label Tea", "Brooke Bond", "Beverages", "500g", 285.0, 310.0, 40,
     "red label tea chai patti tea powder 500g", "Swad apnepan ka classic red label tea 500g"),
    ("Brooke Bond Red Label Tea", "Brooke Bond", "Beverages", "250g", 145.0, 160.0, 40,
     "red label tea chai patti tea powder 250g", "Swad apnepan ka classic red label tea 250g"),
    ("Wagh Bakri Premium CTC Tea", "Wagh Bakri", "Beverages", "500g", 290.0, 315.0, 30,
     "wagh bakri tea chai patti ctc strong tea 500g", "Strong taste and rich colour CTC tea 500g"),
    ("Nescafe Classic Instant Coffee", "Nescafe", "Beverages", "50g Jar", 165.0, 180.0, 35,
     "coffee nescafe instant coffee powder jar 50g", "100% pure instant rich aroma coffee 50g jar"),
    ("Nescafe Classic Instant Coffee", "Nescafe", "Beverages", "100g Jar", 310.0, 340.0, 25,
     "coffee nescafe instant coffee powder jar 100g", "100% pure instant rich aroma coffee 100g jar"),
    ("Bru Instant Coffee", "Bru", "Beverages", "100g", 195.0, 215.0, 35,
     "bru coffee instant filter coffee chicory 100g", "Authentic roasted coffee chicory mix 100g jar"),
    ("Horlicks Classic Malt Health Drink", "Horlicks", "Beverages", "500g", 245.0, 265.0, 25,
     "horlicks health drink milk malt nutrition powder 500g", "Clinically proven nutrition drink for kids 500g jar"),
    ("Boost Energy Drink", "Boost", "Beverages", "500g", 255.0, 275.0, 25,
     "boost energy secret health drink chocolate malt 500g", "Energy fuel malt chocolate drink 500g jar"),
    ("Thums Up Charged Cola", "Thums Up", "Beverages", "750ml", 45.0, 45.0, 40,
     "thumsup cold drink soda soft drink cola 750ml", "Taste the thunder strong fizzy cola 750ml bottle"),
    ("Thums Up Charged Cola", "Thums Up", "Beverages", "2.25 L", 95.0, 99.0, 30,
     "thumsup cold drink soda cola big bottle 2.25l", "Taste the thunder strong cola party size 2.25 litre"),
    ("Coca Cola Original Taste", "Coca Cola", "Beverages", "750ml", 45.0, 45.0, 40,
     "coke cocacola cold drink soda beverage 750ml", "Chilled original taste coca cola 750ml bottle"),
    ("Sprite Lime Soda", "Sprite", "Beverages", "750ml", 45.0, 45.0, 40,
     "sprite cold drink soda lime clear soda 750ml", "Clear lime crisp refreshing soft drink 750ml"),
    ("Maaza Mango Drink", "Maaza", "Beverages", "600ml", 40.0, 40.0, 40,
     "maaza mango juice drink frooti alphonso 600ml", "Real alphonso pulp thick mango drink 600ml"),
    ("Maaza Mango Drink", "Maaza", "Beverages", "1.2 L", 75.0, 80.0, 35,
     "maaza mango juice drink big bottle 1.2l", "Real alphonso pulp thick mango drink 1.2 litre"),
    ("Real Fruit Power Mixed Fruit Juice", "Real", "Beverages", "1 L", 120.0, 135.0, 30,
     "juice real fruit mixed juice tetra pack 1l", "100% real mixed fruit nectar juice 1 litre"),
    ("Bisleri Mineral Water Bottle", "Bisleri", "Beverages", "1 L", 20.0, 20.0, 60,
     "water bottle bisleri mineral water drinking water 1l", "Purified mineral water with added minerals 1 litre"),
    ("Bisleri 20L Water Can", "Bisleri", "Beverages", "20L Can", 80.0, 90.0, 20,
     "water can 20l 20 litre bisleri water jar mineral", "Sealed 20 litre commercial mineral water bubble top can"),

    # --- SNACKS, BISCUITS & INSTANT FOODS ---
    ("Maggi 2-Minute Masala Noodles", "Nestle", "Snacks", "Single Pack (70g)", 14.0, 14.0, 80,
     "maggi noodles masala snacks instant single 70g", "India's favorite 2-minute instant masala noodles 70g"),
    ("Maggi 2-Minute Masala Noodles", "Nestle", "Snacks", "4-Pack (280g)", 56.0, 60.0, 60,
     "maggi noodles masala snacks instant 4 pack 280g", "Classic 2-minute instant masala noodles 4 pack"),
    ("Yippee Magic Masala Noodles", "Sunfeast", "Snacks", "4-Pack (240g)", 52.0, 55.0, 45,
     "yippee noodles sunfeast magic masala 4 pack", "Non-sticky round long masala noodles 4 pack"),
    ("Parle-G Gluco Biscuits", "Parle", "Snacks", "250g", 25.0, 25.0, 70,
     "parleg biscuits chai biscuit snacks glucose 250g", "Classic golden glucose tea biscuits 250g pack"),
    ("Britannia Good Day Butter Cookies", "Britannia", "Snacks", "200g", 35.0, 35.0, 50,
     "goodday biscuits cookies butter snacks 200g", "Rich buttery smiling crunch cookies 200g"),
    ("Britannia Good Day Cashew Cookies", "Britannia", "Snacks", "200g", 40.0, 40.0, 50,
     "goodday biscuits cookies cashew kaju cookies 200g", "Rich cashew nut delight cookies 200g"),
    ("Britannia Marie Gold Biscuits", "Britannia", "Snacks", "300g", 35.0, 38.0, 60,
     "marie gold biscuits chai tea light biscuits 300g", "Crispy light tea-time marie biscuits 300g"),
    ("Oreo Original Chocolate Creme Cookies", "Cadbury", "Snacks", "120g", 35.0, 35.0, 50,
     "oreo biscuits chocolate cream cookies cadbury 120g", "Rich dark chocolate cookies with vanilla creme 120g"),
    ("Sunfeast Dark Fantasy Choco Fills", "Sunfeast", "Snacks", "300g", 110.0, 130.0, 30,
     "dark fantasy biscuits chocolate choco fills molten 300g", "Molten choco cream filled luxury cookies 300g"),
    ("Lay's Classic Salted Potato Chips", "Lay's", "Snacks", "50g", 20.0, 20.0, 50,
     "lays chips salted potato chips blue green snack 50g", "Crispy thinly sliced salted potato chips 50g"),
    ("Lay's India's Magic Masala Chips", "Lay's", "Snacks", "50g", 20.0, 20.0, 50,
     "lays blue chips magic masala spicy potato chips 50g", "Spicy Indian magic masala potato chips 50g"),
    ("Kurkure Masala Munch", "Kurkure", "Snacks", "85g", 20.0, 20.0, 60,
     "kurkure masala namkeen snacks crunchy chips 85g", "Chatpata crunchy corn puff masala munch 85g"),
    ("Haldiram's Aloo Bhujia", "Haldiram's", "Snacks", "200g", 55.0, 60.0, 40,
     "aloo bhujia namkeen haldiram sev spicy potato 200g", "Crispy spiced potato mint noodle namkeen 200g"),
    ("Haldiram's Khatta Meetha Mixture", "Haldiram's", "Snacks", "200g", 55.0, 60.0, 40,
     "khatta meetha mixture namkeen sweet sour haldirams 200g", "Sweet and sour traditional namkeen mixture 200g"),
    ("Act II Instant Popcorn Butter Lovers", "Act II", "Snacks", "33g", 30.0, 35.0, 40,
     "popcorn act 2 act ii butter instant pressure cooker 33g", "3-minute fresh hot buttery popcorn 33g"),

    # --- FRESH VEGGIES & FRUITS ---
    ("Fresh Farm Potatoes", "Farm Fresh", "Veggies", "1kg", 35.0, 40.0, 50,
     "potato aloo bangaladumpa alu veggies vegetables 1kg", "Fresh handpicked farm potatoes 1kg"),
    ("Fresh Crunchy Red Onions", "Farm Fresh", "Veggies", "1kg", 40.0, 45.0, 50,
     "onion pyaz ullipayalu ulli veggies vegetables 1kg", "Fresh pungent red onions 1kg"),
    ("Fresh Crunchy Red Onions", "Farm Fresh", "Veggies", "2kg", 78.0, 90.0, 40,
     "onion pyaz ullipayalu ulli 2kg 2kgs veggies", "Fresh pungent red onions 2kg value bag"),
    ("Fresh Cooking Tomatoes", "Farm Fresh", "Veggies", "1kg", 30.0, 35.0, 50,
     "tomato tamatar tamata veggies vegetables ripe red 1kg", "Juicy firm red cooking tomatoes 1kg"),
    ("Fresh Green Chillies", "Farm Fresh", "Veggies", "250g", 20.0, 25.0, 40,
     "chilli mirchi mirapakayalu spicy veggies green chillies 250g", "Crisp spicy fresh green chillies 250g"),
    ("Fresh Ginger / Adrak / Allam", "Farm Fresh", "Veggies", "250g", 25.0, 30.0, 40,
     "ginger adrak allam fresh spices veggies 250g", "Aromatic clean fresh root ginger 250g"),
    ("Fresh Garlic / Lehsun / Vellulli", "Farm Fresh", "Veggies", "250g", 45.0, 55.0, 40,
     "garlic lehsun vellulli cloves fresh veggies 250g", "Strong white garlic bulbs 250g"),
    ("Fresh Coriander Leaves", "Farm Fresh", "Veggies", "1 Bunch", 15.0, 20.0, 40,
     "coriander kothimeera dhaniya patta fresh herb leaves bunch", "Fresh aromatic green coriander bunch"),
    ("Fresh Mint Leaves / Pudina", "Farm Fresh", "Veggies", "1 Bunch", 15.0, 20.0, 30,
     "mint pudina leaves fresh herb bunch chai chutney", "Fragrant fresh green mint pudina bunch"),
    ("Fresh Juicy Lemons", "Farm Fresh", "Veggies", "Pack of 4", 20.0, 25.0, 40,
     "lemon nimbu nimmakayalu yellow juice citrus 4 pack", "Juicy ripe yellow lemons pack of 4"),
    ("Fresh Robusta Bananas", "Farm Fresh", "Veggies", "1 Dozen (12 pcs)", 60.0, 70.0, 30,
     "banana kela aratpandlu fruit robusta dozen 12 pcs", "Fresh energy rich sweet robusta bananas 1 dozen"),
    ("Shimla Royal Gala Apples", "Farm Fresh", "Veggies", "1kg (4-5 pcs)", 160.0, 185.0, 25,
     "apple seb sev fruits fresh sweet shimla apples 1kg", "Crisp juicy sweet Shimla Royal Gala apples 1kg"),

    # --- CLEANING, HOUSEHOLD & PERSONAL CARE ---
    ("Vim Dishwash Bar", "Vim", "Cleaning", "300g", 25.0, 28.0, 60,
     "vim bar dishwash soap bartan sabun vessel clean lemon 300g", "Powerful grease cleaning lemon dishwash bar 300g"),
    ("Vim Dishwash Liquid Gel Lemon", "Vim", "Cleaning", "500ml", 115.0, 130.0, 40,
     "vim gel dishwash liquid gel bartan utensil wash lemon 500ml", "Concentrated 1-spoon grease cleaning lemon gel 500ml"),
    ("Surf Excel Quick Wash Detergent", "Surf Excel", "Cleaning", "1kg", 145.0, 160.0, 40,
     "surf excel detergent washing powder kapde sabun wash 1kg", "Stain removal quick wash detergent powder 1kg"),
    ("Surf Excel Quick Wash Detergent", "Surf Excel", "Cleaning", "2kg", 280.0, 310.0, 30,
     "surf excel detergent washing powder kapde wash 2kg 2kgs", "Stain removal quick wash detergent powder 2kg value pack"),
    ("Tide Plus Extra Power Detergent", "Tide", "Cleaning", "1kg", 125.0, 140.0, 40,
     "tide detergent powder kapde washing powder lemon 1kg", "Outstanding whiteness extra power detergent 1kg"),
    ("Rin Detergent Bar Soap", "Rin", "Cleaning", "250g", 22.0, 25.0, 60,
     "rin bar soap washing soap kapde sabun white 250g", "Bright clothes detergent laundry bar soap 250g"),
    ("Harpic Power Plus Toilet Cleaner", "Harpic", "Cleaning", "500ml", 95.0, 105.0, 40,
     "harpic toilet cleaner disinfectant bathroom commode 500ml", "10x better germ kill toilet cleaner 500ml"),
    ("Lizol Disinfectant Floor Cleaner", "Lizol", "Cleaning", "500ml", 98.0, 110.0, 40,
     "lizol floor cleaner disinfectant floor wash citrus pine 500ml", "99.9% germ kill floor disinfectant cleaner 500ml"),
    ("Dettol Original Bathing Soap", "Dettol", "Personal Care", "Pack of 3 (3x100g)", 115.0, 130.0, 40,
     "dettol soap bathing soap sabun antiseptic germ protection 3 pack", "Trusted antiseptic germ protection bathing soap 3 pack"),
    ("Lifebuoy Total Germ Protection Soap", "Lifebuoy", "Personal Care", "100g", 35.0, 38.0, 50,
     "lifebuoy soap sabun bathing germ protection 100g", "Total silver shield germ protection soap 100g"),
    ("Dove Cream Beauty Bathing Bar", "Dove", "Personal Care", "100g", 65.0, 72.0, 40,
     "dove soap beauty bar moisturizing gentle 100g", "1/4 moisturising cream gentle beauty bar 100g"),
    ("Colgate Strong Teeth Toothpaste", "Colgate", "Personal Care", "200g", 110.0, 125.0, 45,
     "colgate toothpaste brush daant paste calcium oral care 200g", "Amino Shakti formula strong teeth toothpaste 200g"),
    ("Close Up Red Hot Gel Toothpaste", "Close Up", "Personal Care", "150g", 105.0, 120.0, 40,
     "closeup toothpaste gel paste fresh breath red hot 150g", "Anti-germ mouthwash infused gel toothpaste 150g"),
    ("Parachute 100% Pure Coconut Hair Oil", "Parachute", "Personal Care", "200ml", 85.0, 95.0, 45,
     "parachute coconut oil hair tel kobbarinune pure 200ml", "100% pure edible grade coconut hair oil 200ml bottle"),
    ("Clinic Plus Strong & Long Shampoo", "Clinic Plus", "Personal Care", "175ml", 95.0, 110.0, 40,
     "clinic plus shampoo hair wash milk protein 175ml", "Milk protein infused strong and long shampoo 175ml bottle"),
    ("Head & Shoulders Anti-Dandruff Shampoo", "Head & Shoulders", "Personal Care", "180ml", 175.0, 195.0, 30,
     "head and shoulders shampoo dandruff hair wash 180ml", "Cool menthol anti-dandruff daily shampoo 180ml"),
    ("All Out Ultra Mosquito Vaporizer Refill", "All Out", "Cleaning", "45ml", 85.0, 95.0, 40,
     "allout mosquito refill machar liquid vaporizer 45ml", "Knockdown formula mosquito repellent liquid refill 45ml"),
    ("Homelite Matchboxes", "Homelite", "Cleaning", "Pack of 10", 20.0, 20.0, 50,
     "matchbox match agipette machis matches karapetti 10 pack", "Safety matchboxes value pack of 10"),
]
